// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIMqbMpHyJBxOkzEmuQDcoAgtijbc0DQ0',
    appId: '1:770307244145:android:f141b2f41ca94fe64e5bd0',
    messagingSenderId: '770307244145',
    projectId: 'task3-44d0c',
    databaseURL: 'https://task3-44d0c-default-rtdb.firebaseio.com',
    storageBucket: 'task3-44d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-zFYLTP1nCNhk1eUrBpbEFwnkkCPOT0o',
    appId: '1:770307244145:ios:4982b998193fbcd94e5bd0',
    messagingSenderId: '770307244145',
    projectId: 'task3-44d0c',
    databaseURL: 'https://task3-44d0c-default-rtdb.firebaseio.com',
    storageBucket: 'task3-44d0c.appspot.com',
    iosClientId: '770307244145-bq5ujbfhpkmn2pcnj6go02h5f4com0ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelreservationtask',
  );
}
